INSERT INTO TBL_TIPO_CAMBIO(ID,MONEDA_ORIGEN,MONEDA_DESTINO,TIPO_CAMBIO)
VALUES(1,'SOLES','DOLARES',2.80);

INSERT INTO TBL_TIPO_CAMBIO(ID,MONEDA_ORIGEN,MONEDA_DESTINO,TIPO_CAMBIO)
VALUES(2,'DOLARES','SOLES',3.50);

INSERT INTO TBL_TIPO_CAMBIO(ID,MONEDA_ORIGEN,MONEDA_DESTINO,TIPO_CAMBIO)
VALUES(3,'SOLES','EURO',4.30);