DROP TABLE IF EXISTS TBL_TIPO_CAMBIO;
 
CREATE TABLE TBL_TIPO_CAMBIO (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  MONEDA_ORIGEN VARCHAR(250) NOT NULL,
  MONEDA_DESTINO VARCHAR(250) NOT NULL,
  TIPO_CAMBIO DOUBLE DEFAULT NULL
);